spring:
  datasource:
    username: root
    password: 982210QwE
    url: jdbc:mysql://localhost:3306/movie_api
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"
