spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/movie_api
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ADMIN@gmail.com"
    password: "password123"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
project:
  poster: posters/

base:
  url: "http://localhost:8080"
